# Environments
# SKIP_IMAGE=true|false - skip building image
# SKIP_PUBLISH_QUAY=true|false - skip publishing in Quay
# SKIP_PUBLISH_GHCR=true|false - skip publishing in GitHub
# SKIP_PUBLISH_ECR=true|false - skip publishing in AWS Public ECR

variables:
  - &kaniko_image "gcr.io/kaniko-project/executor:v1.21.1-debug"
  - &skopeo_image "quay.io/containers/skopeo:v1.14.2"
  - &awscli_image "public.ecr.aws/aws-cli/aws-cli:2.15.28"

steps:
  set-env:
    image: debian:bookworm-slim
    commands:
      - .cicd/set-env.sh
  image:
    when:
      evaluate: 'SKIP_IMAGE != "true"'
    image: *kaniko_image
    commands:
      - .cicd/set-docker-auth.sh
      - .cicd/build.sh
    secrets:
      - docker_usr
      - docker_pwd
  publish-quay:
    when:
      evaluate: 'SKIP_PUBLISH_QUAY != "true"'
    image: *skopeo_image
    commands:
      - .cicd/publish-quay.sh
    secrets:
      - quay_creds
  publish-ghcr:
    when:
      evaluate: 'SKIP_PUBLISH_GHCR != "true"'
    image: *skopeo_image
    commands:
      - .cicd/publish-ghcr.sh
    secrets:
      - ghcr_creds
  get-aws-auth:
    when:
      evaluate: 'SKIP_PUBLISH_ECR != "true"'
    image: *awscli_image
    commands:
      - .cicd/get-aws-ecr-pwd.sh
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
  publish-ecr:
    when:
      evaluate: 'SKIP_PUBLISH_ECR != "true"'
    image: *skopeo_image
    commands:
      - .cicd/publish-ecr.sh
