# Environments
# SKIP_IMAGE=true|false - skip building image
# SKIP_PUBLISH_QUAY=true|false - skip publishing in Quay
# SKIP_PUBLISH_GHCR=true|false - skip publishing in GitHub
# SKIP_PUBLISH_ECR=true|false - skip publishing in AWS Public ECR

steps:
  set-env:
    image: debian:bookworm-slim
    commands:
      - .cicd/set-env.sh
  image:
    when:
      evaluate: 'SKIP_IMAGE != "true"'
    image: gcr.io/kaniko-project/executor:v1.20.1-debug
    commands:
      - .cicd/set-docker-auth.sh
      - .cicd/build.sh
    secrets:
      - docker_usr
      - docker_pwd
  publish-quay:
    when:
      evaluate: 'SKIP_PUBLISH_QUAY != "true"'
    image: quay.io/containers/skopeo:v1.14.2
    commands:
      - .cicd/publish-quay.sh
    secrets:
      - quay_creds
  publish-ghcr:
    when:
      evaluate: 'SKIP_PUBLISH_GHCR != "true"'
    image: quay.io/containers/skopeo:v1.14.2
    commands:
      - .cicd/publish-ghcr.sh
    secrets:
      - ghcr_creds
  get-aws-auth:
    when:
      evaluate: 'SKIP_PUBLISH_ECR != "true"'
    image: public.ecr.aws/aws-cli/aws-cli:2.15.23
    commands:
      - .cicd/get-aws-ecr-pwd.sh
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
  publish-ecr:
    when:
      evaluate: 'SKIP_PUBLISH_ECR != "true"'
    image: quay.io/containers/skopeo:v1.14.2
    commands:
      - .cicd/publish-ecr.sh
